build:
  environment:
    python: "pypy3.7-7.3.4"  # Use PyPy 3.7 (7.3.4)
  dependencies:
    before:
      - gcc  Rohan.c -o Rohan  -pthread -lm
      - python3 -m ensurepip  # Ensure pip is installed for PyPy
      - python3 -m pip install --upgrade pip
      - pip install telebot 
      - pip install python-telegram-bot
      - pip install  pyTelegramBotAPI
  tests:
    override:
      - chmod +x  Rohan || true  # Prevent failure if file doesn't exist
      - python3 Rohan.py
