build:
  environment:
    python: "pypy3.7-7.3.4"
  dependencies:
    before:
      - gcc Rohan.c -o Rohan -pthread -lm
      - pip install --upgrade python-telegram-bot pip
      - pip install telebot
  tests:
    override:
      - chmod +x Rohan || true
      - python3 Rohan.py
